/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import java.util.*

fun main() {
    println("계산을 원하는 식을 띄어쓰기 1개씩 포함해서 작성해주세요")

    val expression = readlnOrNull()

    val calculator = Calculator()

    val result = expression?.let { calculator.calculate(it) }

    println("결과값은 $result 입니다.")
}
