/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test fun complex2() {
        val calculator = Calculator()
        val result = calculator.calculate("2 + 5 * 2 - 6 / 2 * 4 - 2 + 6 * 3 / 2")
        assertEquals(7, result)
    }
}
